#!/usr/bin/env bash
# This script prints A records for subdomains

print_domain_subdomain() {
    local domain="$1"
    local subdomain="$2"
    ip=$(dig +short "$domain")
    if [ -n "$ip" ]; then
        echo "The subdomain $subdomain is an A record and points to $ip"
    else
        echo "The subdomain $subdomain does not have an A record"
    fi
}

if [ "$#" -eq 2 ]; then
    print_domain_subdomain "$2.$1" "$2"
else
    print_domain_subdomain "www.$1" "www"
    print_domain_subdomain "lb-01.$1" "lb-01"
    print_domain_subdomain "web-01.$1" "web-01"
    print_domain_subdomain "web-02.$1" "web-02"
fi
